#Component Info
info:
 component: Zuul-Server
 
#Spring Application Name 
spring:
 application:
  name: Zuul-Server 
 
#Server Port
server:
 port: 8765 

#Endpoints 
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  sensitive: false

#Zuul routes active 
zuul: 
 routes:
  public-restservice: 
   path: /public/**
   serviceId: public-restservice
  private-restservice:
   path: /private/**
   serviceId: private-restservice
  swagger:
    path: /swagger/**
    serviceId: swagger
 
#Eureka Instance ID
eureka:
 client:
  serviceUrl:
   defaultZone: ${vcap.services.discovery-service.credentials.uri:http://compeureka:8761}/eureka/
   #defaultZone: http://172.18.0.3:8761/eureka/
 instance:
  instanceId: ${spring.application.name}:${server.port} 

#Ribbon Activation
ribbon:
 eureka:
  enabled: true